name: Docker Test & Publish

on:
  push:
    tags:
      - "*"
  pull_request:
    paths:
      - "Dockerfile"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  GHCR_OWNER: chillboio-studios
  GHCR_REPO: otube-chat-instance

jobs:
  base:
    name: Test base image build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest
          cache-from: type=gha,scope=buildx-base-multi-arch
          cache-to: type=gha,scope=buildx-base-multi-arch,mode=max

  publish:
    name: Publish Docker images
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest

      # API
      - name: Docker meta
        id: meta-api
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/api

      - name: Publish API
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/delta/Dockerfile
          tags: ${{ steps.meta-api.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest
          labels: ${{ steps.meta-api.outputs.labels }}

      # EVENTS
      - name: Docker meta
        id: meta-events
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/events

      - name: Publish Events
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/bonfire/Dockerfile
          tags: ${{ steps.meta-events.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest
          labels: ${{ steps.meta-events.outputs.labels }}

      # FILE SERVER
      - name: Docker meta
        id: meta-files
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/file-server

      - name: Publish File Server
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/services/autumn/Dockerfile
          tags: ${{ steps.meta-files.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest
          labels: ${{ steps.meta-files.outputs.labels }}

      # PROXY
      - name: Docker meta
        id: meta-proxy
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/proxy

      - name: Publish Proxy
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/services/january/Dockerfile
          tags: ${{ steps.meta-proxy.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest
          labels: ${{ steps.meta-proxy.outputs.labels }}

      # GIFBOX
      - name: Docker meta
        id: meta-gifbox
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/gifbox

      - name: Publish Gifbox
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/services/gifbox/Dockerfile
          tags: ${{ steps.meta-gifbox.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest
          labels: ${{ steps.meta-gifbox.outputs.labels }}

      # CROND
      - name: Docker meta
        id: meta-crond
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/crond

      - name: Publish Crond
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/daemons/crond/Dockerfile
          tags: ${{ steps.meta-crond.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest
          labels: ${{ steps.meta-crond.outputs.labels }}

      # PUSHD
      - name: Docker meta
        id: meta-pushd
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/pushd

      - name: Publish Pushd
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/daemons/pushd/Dockerfile
          tags: ${{ steps.meta-pushd.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest
          labels: ${{ steps.meta-pushd.outputs.labels }}

      # VOICE INGRESS
      - name: Docker meta
        id: meta-voice
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/voice-ingress

      - name: Publish Voice Ingress
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/daemons/voice-ingress/Dockerfile
          tags: ${{ steps.meta-voice.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.GHCR_REPO }}/base:latest
          labels: ${{ steps.meta-voice.outputs.labels }}
